import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateInvoicePDF = (invoice, companyDetails) => {
    const doc = new jsPDF();
    const company = companyDetails || { name: 'Your Company', address: 'Your Address', companyEmail: 'contact@company.com' };
    const client = invoice.clientId || { name: 'Client Name', email: 'client@email.com' };

    // --- Header ---
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59); // slate-800
    doc.text('INVOICE', 20, 25);

    // --- Company Info ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(company.name.toUpperCase(), 140, 25);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139); // slate-400
    doc.text(company.address || '', 140, 30);
    doc.text(company.companyEmail || '', 140, 35);
    if (company.gstNumber) doc.text(`GST: ${company.gstNumber}`, 140, 40);

    // --- Horizontal Line ---
    doc.setDrawColor(241, 245, 249); // slate-100
    doc.line(20, 45, 190, 45);

    // --- Invoice Details ---
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO', 20, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(client.name, 20, 60);
    doc.setTextColor(100, 116, 139);
    doc.text(client.email || '', 20, 65);
    if (client.phone) doc.text(client.phone, 20, 70);

    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE #', 140, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(invoice.invoiceNumber, 165, 55);

    doc.setFont('helvetica', 'bold');
    doc.text('DATE', 140, 62);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date(invoice.date).toLocaleDateString(), 165, 62);

    doc.setFont('helvetica', 'bold');
    doc.text('DUE DATE', 140, 69);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date(invoice.dueDate).toLocaleDateString(), 165, 69);

    // --- Table ---
    const tableColumn = ["Description", "Quantity", "Rate", "Amount"];
    const tableRows = invoice.items.map(item => [
        item.description,
        item.quantity,
        `INR ${item.rate.toLocaleString()}`,
        `INR ${item.amount.toLocaleString()}`
    ]);

    doc.autoTable({
        startY: 80,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        headStyles: { 
            fillColor: [30, 41, 59], 
            textColor: [255, 255, 255],
            fontSize: 10,
            fontStyle: 'bold',
            halign: 'left'
        },
        bodyStyles: { 
            fontSize: 9,
            textColor: [51, 65, 85]
        },
        columnStyles: {
            3: { halign: 'right' }, // Amount column right aligned
            2: { halign: 'right' }  // Rate column right aligned
        },
        margin: { left: 20, right: 20 }
    });

    // --- Totals ---
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    
    doc.text('Subtotal:', 140, finalY);
    doc.setFont('helvetica', 'normal');
    doc.text(`INR ${invoice.subTotal.toLocaleString()}`, 190, finalY, { align: 'right' });

    if (invoice.taxTotal > 0) {
        doc.setFont('helvetica', 'bold');
        doc.text('Tax:', 140, finalY + 7);
        doc.setFont('helvetica', 'normal');
        doc.text(`INR ${invoice.taxTotal.toLocaleString()}`, 190, finalY + 7, { align: 'right' });
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL:', 140, finalY + 15);
    doc.text(`INR ${invoice.grandTotal.toLocaleString()}`, 190, finalY + 15, { align: 'right' });

    // --- Status Badge (Optional) ---
    if (invoice.status === 'paid') {
        doc.setDrawColor(34, 197, 94); // emerald-500
        doc.setFillColor(240, 253, 244); // emerald-50
        doc.roundedRect(20, finalY, 40, 15, 3, 3, 'FD');
        doc.setTextColor(21, 128, 61); // emerald-700
        doc.setFontSize(10);
        doc.text('PAID', 40, finalY + 9, { align: 'center' });
    }

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // slate-300
        doc.text('Generated by TeamFlow CRM - Thank you for your business!', 105, 285, { align: 'center' });
    }

    doc.save(`${invoice.invoiceNumber}.pdf`);
};
